### PR TITLE
Remove unnecessary errors related to getting round height in tests

### LINKED ISSUE #336: Clarify the source of errors in logs when testing phase1-coordinator
There are some logs like
```
Aug 11 20:27:42.424 ERROR phase1_coordinator::storage::disk: Locator missing in call to get() in storage.
```
To reproduce:
```bash
cd phase1-coordinator
cargo test --release
```
These logs are confusing and may be misleading because these are not actual errors and most likely a correctly handled behavior

### PR DESCRIPTION
**Pull request by julesdesmit**
The error was caused by immediately using the `get()` call when trying to see if the round height file had been created yet. This will log an error if the file is missing, and thus preceding it with an `exists()` call will silence this error.

Fixes #336

### CODE REVIEW

File: phase1-coordinator/src/coordinator.rs [hunk 1]
```diff
@@ -2199,12 +2199,17 @@ impl Coordinator {
 
     #[inline]
     fn load_current_round_height(storage: &Disk) -> Result<u64, CoordinatorError> {
-        // Fetch the current round height from storage.
-        match storage.get(&Locator::RoundHeight)? {
-            // Case 1 - This is a typical round of the ceremony.
-            Object::RoundHeight(current_round_height) => Ok(current_round_height),
-            // Case 2 - Storage failed to fetch the round height.
-            _ => Err(CoordinatorError::StorageFailed),
+        match storage.exists(&Locator::RoundHeight) {
```
Comment (kellpossible) [inline phase1-coordinator/src/coordinator.rs:2202]: this can be smaller indentation with an `if` - `else` statement, but I don't mind, both are just as readable :slightly_smiling_face:

**Review by kellpossible — APPROVED** [review]
looks good to me

**Comment by kellpossible** [comment]
For other reviewers it might be good to explain how this prevents the error message
