### PR TITLE
Fix for the test with drop of multiple contributors

### LINKED ISSUE #121: Drop Multiple Contributors and Allocate Tasks to Coordinator
Currently, the setup does not handle the case where we need to drop multiple failing contributors and allocate tasks to the coordinator contributor correctly (see`test_coordinator_drop_multiple_contributors` in the features/coordinator-participants branch.  

A solution should reallocate work to the contributor with least load in `add_replacement_contributor_unsafe` in rounds.rs. May need some interleaving logic.

### PR DESCRIPTION
**Pull request by ibaryshnikov**
With this change `coordinator_drop_multiple_contributors_test` now passes.

- [x] fix panic in call to storage
- [x] fix reallocation of tasks for affected contributors
- [ ] ~~assign all tasks left by dropped contributor to a replacement contributor~~

Affected tests which required an update:
- [x] coordinator_drop_contributor_basic_test
- [x] coordinator_drop_contributor_in_between_two_contributors_test
- [x] coordinator_drop_contributor_with_contributors_in_pending_tasks_test
- [x] coordinator_drop_contributor_locked_chunks_test
- [x] coordinator_drop_contributor_removes_contributions
- [x] coordinator_drop_contributor_clear_locks_test
- [x] coordinator_drop_multiple_contributors_test

The fix for task reallocation is described below. Say, we have 2 contributors, 2 buckets, 4 chunks in each bucket. When we make all contributions, the state is:
```
contributor1 assigned tasks length is 0
contributor1 completed tasks length is 8
contributor2 assigned tasks length is 0
contributor2 completed tasks length is 8
```
When we drop contributor 1, the state before the change would be
```
contributor2 assigned tasks length is 8
contributor2 completed tasks length is 0
contributor2 disposed tasks length is 4
```
After the change from this PR the state would be
```
contributor2 assigned tasks length is 4
contributor2 completed tasks length is 0
contributor2 disposed tasks length is 4
```

Closes #121

### CODE REVIEW

File: phase1-coordinator/src/coordinator_state.rs [hunk 1]
```diff
@@ -1892,43 +1893,53 @@ impl CoordinatorState {
...
+                let new_assigned_tasks =
+                    initialize_tasks(contributor_info.bucket_id, number_of_chunks, number_of_contributors);
 
-                    break;
-                }
+                // Reassign tasks for the affected contributor.
+                contributor_info.assigned_tasks = new_assigned_tasks
+                    .into_iter()
+                    .filter(|task| !tasks_to_exclude.contains(&task.chunk_id))
+                    .collect();
```
Comment (howardwu) [inline phase1-coordinator/src/coordinator_state.rs:1942]: Can you combine these operations for easier readability?

File: phase1-coordinator/src/coordinator_state.rs [hunk 2]
```diff
@@ -1892,43 +1893,53 @@ impl CoordinatorState {
...
-                    contributor_info
-                        .disposed_tasks
-                        .extend(contributor_info.completed_tasks.iter());
-                    contributor_info.assigned_tasks = LinkedList::new();
-                    contributor_info.completed_tasks = LinkedList::new();
+                all_disposed_tasks.extend(contributor_info.disposed_tasks.iter());
 
-                    // Add the disposed tasks to the cumulative disposed tasks.
-                    disposed_tasks.extend(contributor_info.disposed_tasks.iter());
+                let mut tasks_to_exclude: HashSet<u64> =
```
Comment (howardwu) [inline phase1-coordinator/src/coordinator_state.rs:1931]:
```suggestion
                // Determine the excluded tasks, which are filtered out from the list of newly assigned tasks.
                let mut tasks_to_exclude: HashSet<u64> =
```

Comment (howardwu) [inline phase1-coordinator/src/coordinator_state.rs:1931]: Can you rename this variable to `excluded_tasks`?

**Review by howardwu — CHANGES_REQUESTED** [review]

File: phase1-coordinator/src/coordinator_state.rs (hunk 1 above)
Comment (ibaryshnikov) [reply phase1-coordinator/src/coordinator_state.rs:1942]: You mean to remove intermediate variable `new_assigned_tasks`?

Comment (howardwu) [reply phase1-coordinator/src/coordinator_state.rs:1942]: Indeed!

File: phase1-coordinator/src/coordinator_state.rs [hunk 3]
```diff
@@ -1892,43 +1893,52 @@ impl CoordinatorState {
...
-                    contributor_info.disposed_tasks = contributor_info.assigned_tasks.clone();
-                    contributor_info
-                        .disposed_tasks
-                        .extend(contributor_info.completed_tasks.iter());
-                    contributor_info.assigned_tasks = LinkedList::new();
-                    contributor_info.completed_tasks = LinkedList::new();
-
-                    // Add the disposed tasks to the cumulative disposed tasks.
-                    disposed_tasks.extend(contributor_info.disposed_tasks.iter());
+            // A hashmap where the key is chunk id and the value is the the contribution id
```
Comment (howardwu) [inline phase1-coordinator/src/coordinator_state.rs:1900]:
```suggestion
            // A HashMap of tasks represented as (chunk ID, contribution ID) pairs.
```

**Review by howardwu — APPROVED** [review]
